# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9514375fc8be129c10b6a1fd68e5dcc20be41ebf8b28703cf07833bc0db8e9538cd88521da03fcd44752b89ee6771b06cfa0b60072d4363eac323984d70473c7

test:
  secret_key_base: ebabc88e18bd34bc00fd497137cb9e37b30dfd1a6e3c727573fbf8aa7572435d14a083df04c656cc99a5baa08c99a35f81d35b32b9c0453ac9809b1ecbc8229b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
